build:
    image: python:2.7
    commands:
        - pip install pep8 pyflakes Django
        - python setup.py test
        - make coverage
        - pep8 --exclude=migrations src
        - pyflakes src
