build:
    image: python:2.7
    commands:
        - pip install pep8 pyflakes Django
        - python setup.py test
        - pep8 --exclude=migrations src
        - pyflakes src
#        - apt-get install python-coverage
#        - make coverage
